language: cpp
cache:
  apt: true
os:
  - linux
sudo: required
dist: trusty
services:
  - docker
addons:
  apt:
    packages:
      - build-essential
      - cmake
      - g++
      - clang
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libminiupnpc-dev
      - libssl-dev
compiler:
  - gcc
script: |
  cd build
  cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Release} ${CMAKE_FLAGS}
  make
matrix:
  include:
    - env: BUILD_TYPE=Release CMAKE_FLAGS="-DWITH_UPNP=ON"
    - env: BUILD_TYPE=Release CMAKE_FLAGS="-DWITH_UPNP=OFF"
    # Make sure Docker containers still build
    - script: cat build/docker/ubuntu:trusty/Dockerfile | docker build -t i2pd/ubuntu:trusty -
    - script: cat build/docker/fedora:23/Dockerfile | docker build -t i2pd/fedora:23 -
